# Generated by Django 5.2.7 on 2025-10-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Flujo')),
                ('query_nl', models.TextField(verbose_name='Consulta en Lenguaje Natural')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flujo de Trabajo',
                'verbose_name_plural': 'Flujos de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de OpenStreetMap')),
                ('data', models.JSONField(help_text='Datos JSON obtenidos del POI/Elemento.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Resultado de Query',
                'verbose_name_plural': 'Resultados de Query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='Número de Paso')),
                ('action', models.CharField(choices=[('NLP_EXTRACT', 'Extracción NLP'), ('OVERPASS_QUERY', 'Consulta Overpass'), ('SELENIUM_PROCESS', 'Procesamiento Selenium'), ('EXPORT_CSV', 'Exportar CSV/BI')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Parámetros para la acción (e.g., el query QL generado).')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Paso de Flujo',
                'verbose_name_plural': 'Pasos de Flujo',
                'ordering': ['step_number'],
            },
        ),
    ]
