# Generated by Django 5.2.7 on 2025-10-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_result_id_alter_workflow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='export_file_path',
            field=models.CharField(blank=True, max_length=512, verbose_name='Ruta del archivo exportado'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('EXPORTED', 'Exportado')], default='PENDING', max_length=10),
        ),
    ]
