# Generated by Django 5.2.7 on 2025-10-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_export_file_path_alter_workflow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['created_at'], 'verbose_name': 'Paso de Flujo', 'verbose_name_plural': 'Pasos de Flujo'},
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
