# Generated by Django 5.2.7 on 2025-10-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflow_options_delete_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error'),
        ),
    ]
